### PR TITLE
add sponsor logo image carousel

### PR DESCRIPTION
**Pull request by matthewthomsonnz**
In a [previous PR](https://github.com/shift72/core-template/pull/320) we added sponsor images to a film detail page. This PR adds this to carousel also.

- upload a 'sponsor' type image to a film to see it (point template to staging-store.shift72.com a couple already uploaded)
- also set custom field: "sponsor_image_text_film" to add text above it
- [AB#5032](https://dev.azure.com/S72/SHIFT72/_boards/board/t/Web%20team/Stories/?workitem=5032)
- [Designs](https://app.zeplin.io/project/5fdaa165fbacf584a2ce4f8b/screen/6209be832a8eafa8366b818c)

### CODE REVIEW

**Review by smitsanghvi21 — COMMENTED** [review]
I feel the client might want us to make the default size of the sponsor image bit smaller than the logo for the mobile devices. Or the other way around it takes a lot of space in the carousel and might want it to be reduced which would cause some support debt.  https://app.zeplin.io/project/5fdaa165fbacf584a2ce4f8b/screen/6209be7256e158598c811277

**Review by brynyShift72 — COMMENTED** [review]
@curtisadams28 has his carousel redesign coming in very soon. This piece of work might need to wait for that before merge incase of any conflicts?

**Comment by matthewthomsonnz** [comment]
> I feel the client might want us to make the default size of the sponsor image bit smaller than the logo for the mobile devices. Or the other way around it takes a lot of space in the carousel and might want it to be reduced which would cause some support debt. https://app.zeplin.io/project/5fdaa165fbacf584a2ce4f8b/screen/6209be7256e158598c811277

@smitsanghvi21 We have to stick with the size in the designs unfortunately. Is there anything you want me to add though?

CSS to do what you're asking isn't too bad, just adding these two image rules:
image

**Review by PeculiarGoat — COMMENTED** [review]
This looks pretty good.

I'm curious what happens in a worst case scenario overflowing carousel item because we are now pushing the carousel height to it's limit.

What happens if everything is filled out to the max (sponsor logo, title, release year, classifications/tagline, availability, subscribe/rent/buy buttons, wishlist button, share button, synopsis)?  I have a feeling that it can't all fit.

**Comment by curtisadams28** [comment]
> This looks pretty good.
> 
> I'm curious what happens in a worst case scenario overflowing carousel item because we are now pushing the carousel height to it's limit.
> 
> What happens if everything is filled out to the max (sponsor logo, title, release year, classifications/tagline, availability, subscribe/rent/buy buttons, wishlist button, share button, synopsis)? I have a feeling that it can't all fit.

@PeculiarGoat It goes underneath the nav and off the top of the page.
image

**Comment by brynyShift72** [comment]
> > This looks pretty good.
> > I'm curious what happens in a worst case scenario overflowing carousel item because we are now pushing the carousel height to it's limit.
> > What happens if everything is filled out to the max (sponsor logo, title, release year, classifications/tagline, availability, subscribe/rent/buy buttons, wishlist button, share button, synopsis)? I have a feeling that it can't all fit.
> 
> @PeculiarGoat It goes underneath the nav and off the top of the page. image

@curtisadams28 can we get a mobile view as well, it might support even less

**Comment by curtisadams28** [comment]
Some better screen shots
Screenshot 2022-05-06 150016
Screenshot 2022-05-06 145914

**Comment by stajs** [comment]
I don't think the title is a fair representation - we are going to line-clamp it, yeah?

**Comment by curtisadams28** [comment]
> I don't think the title is a fair representation - we are going to line-clamp it, yeah?
Yeah. I was just demonstrating what will happen when there's too much content in the carousel.

**Review by curtisadams28 — APPROVED** [review]
LGTM. Once this is in develop, I will merge it into the new-carousel.

**Pull request merged**
