### PR TITLE
Langs ru to zh

### PR DESCRIPTION
**Pull request by stajs**

### CODE REVIEW

**Review by brynyShift72 — COMMENTED** [review]
Are dropping `wcag_skip_links_footer": { "other": "Skip to Footer" },` ?

**Comment by curtisadams28** [comment]
> Are dropping `wcag_skip_links_footer": { "other": "Skip to Footer" },` ?

Yes. The new skip link does not use it.

**Review by brynyShift72 — CHANGES_REQUESTED** [review]
RU and TR:
`"validation_pincode_required": { "other": "Please enter a PIN code." }`
`"shopping_error_discount_worn_out": { "other": "That promo code can no longer be used." }`

**Review by l0ud0gg — APPROVED** [review]
lgtm. just check brynys comments. also merge in from develop again to fix merge conflicts

**Comment by stajs** [comment]
@brynyShift72 and @l0ud0gg thanks for the eyeballs, I've fixed those so gonna merge.

**Pull request merged**
