### PR TITLE
changed nav gradient

### PR DESCRIPTION
**Pull request by PeculiarGoat**
ADO card: ☑️ [AB#9635](https://dev.azure.com/S72/fefacba9-96b6-4af2-a53d-050ed453e13a/_workitems/edit/9635)

Designs: 
- https://app.zeplin.io/project/5fdaa165fbacf584a2ce4f8b/screen/6316b1d45d252d1682cdfdef

## Description of work
Made the nav taller so the gradient can also be taller.

## Edge cases/Caveats/Known issues
- Background images on light theme sites appear washed out.
image image
- Background images on dark theme sites appear gloomy. 
image 
image

### Affected Clients
 - All clients with background/carousel images.

## Checklist
- [x] CI tests are passing Github actions (inc. linting)
- [x] Key areas of the feature outlined for context and testing
- [x] If there are designs for this work are they noted here and in the ADO card 
- [x] Design review
- [x] Have checked this at multiple screen resolutions and range of browsers
- [x] Moved ADO card to Dev/done, checked link to Github, tagged "Review"
- [x] Updated changelog (if applicable)
- [x] I promise to document any new feature toggles/configurations in the appropriate documentation

### CODE REVIEW

**Comment by matthewthomsonnz** [comment]
On some common screen resolutions the image is gloomy all over on carousel (image has some gradient shadow on every part, screenshot below). Your attached design shows a gradient to zero opacity/totally visible at the bottom. 

[There is a design](https://app.zeplin.io/project/5fdaa165fbacf584a2ce4f8b/screen/6316b2d2cd7249102bbc954f) for how the carousel is expected to look with no opacity in the middle. I'm going to assume they want it to look like this at max height of how as that would push the title etc below viewport. This design assumes one single gradient to be applied over top that resizes vertically to height of carousel.

I think this card needs to implement that one gradient. Maybe even with a height of `calc(100vh - 100px)` + max height as per designs



image

**Comment by PeculiarGoat** [comment]
@matthewthomsonnz I'm confused... isn't the carousel the same height across all breakpoints?

**Comment by matthewthomsonnz** [comment]
> @matthewthomsonnz I'm confused... isn't the carousel the same height across all breakpoints?

It appears that height changes with viewport height

**Comment by PeculiarGoat** [comment]
Yikes... add that to list of reasons to start a new template from scratch.

Well the gradient can't change height unless the nav changes height... it doesn't care about the carousel.  The goal of this task is to guarantee the contrast of nav text for accessibility at the expense of clear background images.

**Comment by matthewthomsonnz** [comment]
> Yikes... add that to list of reasons to start a new template from scratch.
> 
> Well the gradient can't change height unless the nav changes height... it doesn't care about the carousel. The goal of this task is to guarantee the contrast of nav text for accessibility at the expense of clear background images.

Oh yep, I think we need to ask for a design for worst case scenario. Perhaps request a design from them with this screenshot?
image

**Comment by PeculiarGoat** [comment]
@matthewthomsonnz Bex is okay with this.

**Comment by additiverich** [comment]
> @matthewthomsonnz Bex is okay with this.

OK with the worst case scenario?

**Comment by additiverich** [comment]
Does this pass muster @matthewthomsonnz?

**Review by matthewthomsonnz — APPROVED** [review]
@additiverich we've definitely missed the mark here but I'll approve anyway. It would've been nice to get more justification

fyi 1366×768 users (8.44% worldwide) will get this experience

**Comment by additiverich** [comment]
@matthewthomsonnz When you say "missed the mark", do you think we've done the wrong thing?

**Comment by PeculiarGoat** [comment]
I do... this task should've been binned.

**Comment by matthewthomsonnz** [comment]
> @matthewthomsonnz When you say "missed the mark", do you think we've done the wrong thing?

100%. Both with approach, and our process/communication with design

**Comment by additiverich** [comment]
Let's hold off on merging then @PeculiarGoat @matthewthomsonnz

**Pull request closed without merging**
