### PR TITLE
feat(improvements): bundle page redesign

### PR DESCRIPTION
**Pull request by PeculiarGoat**
replaced bundle page HTML

replaced bundle page CSS

atomised bundle page jets to reduce impact of client customisation

### CODE REVIEW

**Comment by PeculiarGoat** [comment]
A few notes:

- Some of the new jets in the `site/templates/bundle` directory will eventually be moved somewhere else to be shared with other pages.
- The CSS is built over what was already there rather than from scratch so it's a bit hacky.  I don't think it's worth starting over with the CSS until everything in core-template is has been atomised and all of the dud classes are stripped out of the html.

**Review by stajs — CHANGES_REQUESTED** [review]
Requesting changes just cause I dislike the jet `{{ spacing }}`. I would prefer we collapse those.

Otherwise looks mostly good, although I question the value on the smaller atoms like title/synopsis.

**Comment by PeculiarGoat** [comment]
The value of the smaller atoms is equal to all of the other atoms.  If the title/synopsis atoms are removed and a client requests a custom title/synopsis then we would have to freeze item.jet in time as is the current process.

**Comment by PeculiarGoat** [comment]
@stajs Are you happy for this to be merged?  It will skip the need for that bundle button alignment task.

**Review by stajs — APPROVED** [review]

**Comment by stajs** [comment]
@PeculiarGoat Yep, happy to merge.

I don't think all atoms are created equal. My dubiosity of their value is due to how unlikely I think a client will ask for changes of that.

**Pull request merged**
