### PR TITLE
AB#4858 Added Sign Out Links

### PR DESCRIPTION
**Pull request by curtisadams28**
I added links inside the s72-sign-out component so that you can select it with keyboard controls.

### CODE REVIEW

**Review by PeculiarGoat — CHANGES_REQUESTED** [review]
Couple of things:

- Please use `href="#"` so it is explicit that these links don't go anywhere (the Relish component overrides redirects here anyway).
- The focus styles for the signout button (for mobile and desktop) are different to the other account buttons... probably want to fix that.

**Comment by PeculiarGoat** [comment]
There are still focus ring issue:

- In desktop view when tabbing through the account menu, the signout button's focus ring is a different shape/size to the others and the hover colour doesn't get activated.
- In mobile view, the same happens but maybe that signout button should have `display: none;` since there is the extra mobile signout button ... more duplication :(

**Review by stajs — APPROVED** [review]
I don't see anything wrong here - @PeculiarGoat do you still need your comments addressed?

**Comment by curtisadams28** [comment]
@PeculiarGoat I've fixed the issues you mentioned. Not sure why that check is failing.

**Comment by PeculiarGoat** [comment]
When I run it locally I get this:
image

Guessing that wasn't your intention lol.

Also not seeing any difference with the borked focus rings/colours on the dropdown signout button.

**Comment by PeculiarGoat** [comment]
Also, don't worry about the checks... we are going to have to live with some failures while I figure out the linter kinks.

**Comment by curtisadams28** [comment]
@PeculiarGoat The site must have been cached when I reordered the css. Fixed now.

**Review by PeculiarGoat — APPROVED** [review]
Nice work!  :+1:

**Pull request merged**
