### PR TITLE
change the font weight for primary buttons from bold to normal

### PR DESCRIPTION
**Pull request by imran-salim**
[AB#5095](https://dev.azure.com/S72/SHIFT72/_workitems/edit/5095)

### CODE REVIEW

**Review by PeculiarGoat — COMMENTED** [review]
@imran-salim There shouldn't be a `package-lock.json` diff in this PR.

Also, I've added a comment for Bex to the card... I think she is confused so hold off on merging this until she clarifies what she wants please!

**Comment by smitsanghvi21** [comment]
@imran-salim You can add the files which doesn't need to be there in a PR in `.gitignore`

**Comment by imran-salim** [comment]
Bex asked for all the button font weights to be changed from 500 to 400.

**Review by stajs — APPROVED** [review]

**Comment by stajs** [comment]
@PeculiarGoat @imran-salim The point on the `package-lock.json` - it will change if peoples installed NPM versions are not aligned. [ATM the `"lockfileVersion": 1`](https://github.com/shift72/core-template/blob/primary-button-font-weight/package-lock.json#L4) indicates the last person to `npm i` has an older version. [Previous versions were `"lockfileVersion": 2`](https://github.com/shift72/core-template/blob/d110f319470aed3d2ffb9b51a05a466cb28e5920/package-lock.json#L4).

We should get back to v2 (not necessarily as part of this PR) and then stop people from downgrading it.

**Pull request merged**
