### PR TITLE
AB#6124 add subscribe_to_watch translation

### PR DESCRIPTION
**Pull request by twln1**
[Core template PR](https://github.com/shift72/core-template/pull/331) with the subscribe button work

Translations were causing merge conflicts so this branch is purely for the required translation

### CODE REVIEW

**Comment by PeculiarGoat** [comment]
I'm confused... can't you just resolve the conflicts in the other branch?

**Comment by twln1** [comment]
@PeculiarGoat I tried but github wasn't happy with it but my environment didn't have any issues with it. I'm pretty confused too

**Comment by PeculiarGoat** [comment]
Why not try merging this branch into the other branch and see what the conflict looks like?

**Comment by stajs** [comment]
@twln1 @PeculiarGoat Can this branch be deleted now?

**Pull request merged**
