### PR TITLE
Translations relish split

### PR DESCRIPTION
**Pull request by brynyShift72**
ADO card: ☑️ [AB#9329](https://dev.azure.com/S72/SHIFT72/_workitems/edit/9329)

Elab notes/AC: 📃 [Google Docs](https://docs.google.com/document/d/11svAR84B4KcYdYIQju41HlQXsMgeXq9r8tZKoDuN_QE/edit#heading=h.bny0ht7u7uqz)
- [☑️ ] Has this been discussed with Delivery Team?

## Description of work
Split out translation keys that were used by Core-template and Relish to remove overlapping usage. Updated .jet files to use the core-template specific keys

### CODE REVIEW

**Review by smitsanghvi21 — APPROVED** [review]
looks good, but I think `nav_search_control_sr_submit` should be `nav_search_control_search_submit` or `nav_search_control_submit`

**Review by PeculiarGoat — APPROVED** [review]
These aren't breaking changes because the keys are all completely new right?  LGTM!

**Comment by brynyShift72** [comment]
> 

All new

**Comment by smitsanghvi21** [comment]
Are you also gonna replace the keys in the db as well?

**Comment by PeculiarGoat** [comment]
@smitsanghvi21 no need... these are all new keys.

**Review by l0ud0gg — APPROVED** [review]
Approved, on the condition the new keys are added to the db also. Nit pick : some in consistent spacing of ":{" ": {" in the jsons.

**Pull request merged**
