### PR TITLE
Ab#5001 move engagement icons

### PR DESCRIPTION
**Pull request by matthewthomsonnz**
Card[ here](https://dev.azure.com/S72/SHIFT72/_boards/board/t/Core%20team/Stories/?workitem=5001)
To view and test, you will need [this branch of relish ](https://github.com/indiereign/shift72-web/pull/246)
Adds share button functionality as[ per these designs](https://app.zeplin.io/project/5fdaa165fbacf584a2ce4f8b/dashboard?q=share)

### CODE REVIEW

**Comment by smitsanghvi21** [comment]
Looks good. Couple of notes:

- The alignment looks bit off (Mac OS 12, MacBook Pro).
- A previous story was added to hide social media icons based on user selection in the [admin](https://dev.azure.com/S72/SHIFT72/_workitems/edit/5854/)  which involved changes to the social-media.jet file. Seems like this isn't going to work at all and I might need to discard the changes in the admin? @stajs @PeculiarGoat 
Screen Shot 2021-11-29 at 1 42 48 PM

**Review by smitsanghvi21 — APPROVED** [review]

**Comment by additiverich** [comment]
https://user-images.githubusercontent.com/3870133/143957008-f3b21794-af00-43ce-bab8-02205f46539d.mov

There's bound to be feathers ruffled if this doesn't match the designs more I reckon

**Comment by matthewthomsonnz** [comment]
> Looks good. Couple of notes:
> 
> * The alignment looks bit off (Mac OS 12, MacBook Pro).
> * A previous story was added to hide social media icons based on user selection in the [admin](https://dev.azure.com/S72/SHIFT72/_workitems/edit/5854/)  which involved changes to the social-media.jet file. Seems like this isn't going to work at all and I might need to discard the changes in the admin? @stajs @PeculiarGoat

Cheers @smitsanghvi21 . I've aligned the icons in the relish branch.

No need to discard changes, the hide user icons functionality has been passed into the relish component.

**Comment by matthewthomsonnz** [comment]
> Screen.Recording.2021-11-30.at.12.08.09.PM.mov 
> There's bound to be feathers ruffled if this doesn't match the designs more I reckon

Line height added

**Review by stajs — COMMENTED** [review]
Do we not care about other language translations? I would expect a PR to cover all languages.

Was there an elab on this card? Delivery team should have been looped in before you started.

What counts as an "engagement icon"? The linked designs only show a social sharing modal. Can you set up a session to walk us through the changes? I can look at screeds of CSS diffs but it doesn't really tell me the impact and if I take the time to set up the right branches of core-template and relish I could still not notice changes that you could easily call out.

**Comment by stajs** [comment]
Also, need changelog updated

**Comment by matthewthomsonnz** [comment]
> Do we not care about other language translations? I would expect a PR to cover all languages.

I thought we are using a translation service now? Or I heard something about the google translate API? As manual was laborious

> Was there an elab on this card? Delivery team should have been looped in before you started.

There was not, but there absolutely should have been. I assumed you guys we're aware core template cards in our boards before they were put there, I'll make a note to bring this up at standup on Monday and flick you a message after.

> What counts as an "engagement icon"? The linked designs only show a social sharing modal. Can you set up a session to walk us through the changes? I can look at screeds of CSS diffs but it doesn't really tell me the impact and if I take the time to set up the right branches of core-template and relish I could still not notice changes that you could easily call out.

Business speak for social/share icons. Can do, who should I invite and when?

**Comment by PeculiarGoat** [comment]
If you add translation keys to core-template... you add them for all languages.  There is no way to cut this corner.

**Comment by matthewthomsonnz** [comment]
> If you add translation keys to core-template... you add them for all languages. There is no way to cut this corner.

@PeculiarGoat  @stajs As mentioned, translation service, or [automation](https://www.npmjs.com/package/google-translate-open-api).

**Comment by matthewthomsonnz** [comment]
> Also, need changelog updated

updated

**Comment by stajs** [comment]
Thanks for the changelog.

Automation would be nice, but we only have the manual labour method atm. "Translation service" could be ambiguous, we're working on allowing self-service translations for a users site, but the underlying core base translations still need to be vaguely correct for each key/language. A simplistic (manual) Google Translate is acceptable. There's been no talk of the Google Translate API that I recall.

Appreciate if you raise the cross-team comms point, I do the same on my side.

For the session, I reckon invite the whole team. There's no harm in everyone being aware of the changes and we'll have to talk clients through differences as they are upgraded.

**Comment by stajs** [comment]
@matthewthomsonnz Just to be explicit, can you add the translations for the other languages too?

**Comment by matthewthomsonnz** [comment]
@stajs sounds good.

Cool I've set up a meeting for 11am Monday. And yep will add the translations.

**Pull request merged**
