### PR TITLE
S72 element switcher

### PR DESCRIPTION
**Pull request by matthewthomsonnz**
This PR:
- Adds component that toggles between Short/Long description divs via button
- does nothing unless `"element_switcher_enabled" = "true"`
- must point to the latest version of relish to work
- Also please view the changes below with GitHub diff setting 'ignore whitespace'

[AB#4745](https://dev.azure.com/S72/SHIFT72/_boards/board/t/Web%20team/Stories/?workitem=4745)

### CODE REVIEW

**Comment by smitsanghvi21** [comment]
@matthewthomsonnz Is it enabled for staging-store.shift72.com or any other site?

**Review by PeculiarGoat — CHANGES_REQUESTED** [review]
Couple of issues:

- No keyboard control.
- There is a bug in the Relish component [here](https://github.com/indiereign/shift72-web/blob/3dd8760e33268e4ada2c531d2fce9416e40d2ee8/src/ui/element-switcher/element-switcher.component.js#L62).  Should be i18n(`meta_description_${this.state.collapsed ? 'expand' : 'collapse'}`).  However, I want to argue against the use of a compound key because it makes searching for keys in codebases a pain in the arse.  I would suggest something like this instead:
```
const META_DESCRIPTION_EXPAND = 'meta_description_expand';
const META_DESCRIPTION_COLLAPSE = 'meta_description_collapse';
<div>{i18n(this.state.collapsed ? META_DESCRIPTION_EXPAND : META_DESCRIPTION_COLLAPSE)}</div>
```

**Comment by matthewthomsonnz** [comment]
> Couple of issues:
> 
> * No keyboard control.
> * There is a bug in the Relish component [here](https://github.com/indiereign/shift72-web/blob/3dd8760e33268e4ada2c531d2fce9416e40d2ee8/src/ui/element-switcher/element-switcher.component.js#L62).  Should be i18n(`meta_description_${this.state.collapsed ? 'expand' : 'collapse'}`).  However, I want to argue against the use of a compound key because it makes searching for keys in codebases a pain in the arse.  I would suggest something like this instead:
> 
> ```
> const META_DESCRIPTION_EXPAND = 'meta_description_expand';
> const META_DESCRIPTION_COLLAPSE = 'meta_description_collapse';
> <div>{i18n(this.state.collapsed ? META_DESCRIPTION_EXPAND : META_DESCRIPTION_COLLAPSE)}</div>
> ```

Quality observations. I've made a relish PR for your approval please:
https://github.com/indiereign/shift72-web/pull/262

**Comment by matthewthomsonnz** [comment]
> @matthewthomsonnz Is it enabled for staging-store.shift72.com or any other site?

@smitsanghvi21 it is now. cheers

**Comment by matthewthomsonnz** [comment]
@smit @PeculiarGoat bump. Approve or request more changes when you can. This can be merged into develop without relish release as is behind feature toggle

**Comment by stajs** [comment]
@matthewthomsonnz replacing @smitsanghvi21 (on vacay) with @curtisadams28.

FYI for someone who has already reviewed like @PeculiarGoat, the best option would be to hit the "re-request review" button when you are ready, but since you've lumped the bump (bump-lumped?) in with another who hasn't reviewed (but yeah isn't here) I'll let it slide 😉

**Comment by PeculiarGoat** [comment]
@matthewthomsonnz this PR is blocked on the Relish one being merged and released right?  Those conflicts need to be resolved too!

**Review by PeculiarGoat — APPROVED** [review]
:+1:

**Pull request merged**
