### PR TITLE
CSS fix for new My Account layout

### PR DESCRIPTION
**Pull request by additiverich**
- pin code-specific CSS changes in _pin-codes.scss
- user account form changes in _shift72.scss
- variable for spacing buttons in the modal in _variables.scss
- include _pin_codes.scss in main.scss (and some whitespace changes)

### CODE REVIEW

**Comment by additiverich** [comment]
Screen Shot 2020-11-12 at 4 00 52 PM

**Comment by PeculiarGoat** [comment]
What's going on in `site/styles/main.scss` ?  Tabs?

**Comment by additiverich** [comment]
Ignore whitespace & there aren't any changes! It's like magic.

**Review by PeculiarGoat — APPROVED** [review]
Cool :+1:

**Comment by additiverich** [comment]
Saved with spaces now

**Review by stajs — APPROVED** [review]

**Review by PeculiarGoat — APPROVED** [review]
We can live without `account_form_masked_pin` since it has a default in Relish... cue the client who wants `****` translated...

**Pull request merged**
