### PR TITLE
Idea for admin start

### PR DESCRIPTION
**Pull request by stajs**
Just an idea, instead of having these scripts being called like:

```
npm start
npm run start-admin
```

... we could use arguments like this:

```
npm start
npm start --admin
```

P.S. `run-p` is shorthand for `npm-run-all --parallel`.

I added a `kibble:start` that always `mkdir`'s (why not?) and tests for the `--admin` flag and chooses either `kibble:watch` or `kibble:watch-admin`. I only broke it out this way so I could do some fancy schmancy console coloring, but `kibble:watch-admin` is simply calling back to `kibble:watch` and passing in it's own `--admin` flag. So `kibble:start` could be just:

```
... npm run kibble:watch -- --admin || npm run kibble:watch
```

---

image
image

### CODE REVIEW

**Comment by stajs** [comment]
Speaking of colors, we should colorize that `api key has expired` - I'm always getting caught out sat waiting for things to run when that scrolls past and don't see it.

**Comment by brynyShift72** [comment]
I like this way better just wondering:
Can you help me understand the `&& test -n \"$npm_config_admin\"` I assume that this is checking for the --admin argument some how?

**Comment by brynyShift72** [comment]
I like this way better just wondering:
Can you help me understand the `&& test -n \"$npm_config_admin\"` I assume that this is checking for the --admin argument some how?

**Comment by stajs** [comment]
- The flag in `npm start --admin`: [a flag without a value gets set to true](https://docs.npmjs.com/cli/v7/using-npm/config#command-line-flags) and then is [available as an environment variable](https://docs.npmjs.com/cli/v7/using-npm/config#environment-variables) which is snake_cased and prefixed with `npm_config_` so `--admin` becomes `$npm_config_admin`. If the flag is not specified then this environment variable is empty.
- Wrapping in double-quotes to turn it to a string `\"$npm_config_admin\"`.
- `test` is a shorter syntax than an if/else block and `-n` is true if the string is non-zero length.

**Comment by brynyShift72** [comment]
Sweet, good to know : )

**Review by PeculiarGoat — APPROVED** [review]
LGTM

**Review by brynyShift72 — APPROVED** [review]

**Review by l0ud0gg — APPROVED** [review]

**Review by smitsanghvi21 — APPROVED** [review]

**Comment by stajs** [comment]
Converted usages (where possible) to shorthand versions of `npm-run-all` to allow logging output of task name.

**Pull request merged**
