### PR TITLE
add urlMapService

### PR DESCRIPTION
**Pull request by twln1**
Supporting work for [this PR](https://github.com/indiereign/shift72-web/pull/284)

This work is to support the [SVOD customer journey](https://dev.azure.com/S72/SHIFT72/_workitems/edit/6124) work. The intention is to provide a way to request the route for a slug without having to hit the APIs

### CODE REVIEW

**Review by additiverich — COMMENTED** [review]
lgtm

**Review by brynyShift72 — APPROVED** [review]
lgtm, does this need to wait on a relish release before being merged?

**Comment by stajs** [comment]
Yes, converting to draft to prevent accidental merging. If you need to do some testing, before merging/releasing reach out in Slack for Verdaccio docs.

**Review by curtisadams28 — APPROVED** [review]

**Review by smitsanghvi21 — APPROVED** [review]

**Comment by twln1** [comment]
@stajs To be clear - by a release are you meaning a prod relish release?

**Comment by stajs** [comment]
@twln1 No, I meant if you needed to test the NPM package of this branch before it was merged and a new core-template is pushed to the NPM registry then you can do so with a local NPM registry (Verdaccio).

But once the matching Relish PR is released to prod, we can unblock this one from being merged.

**Comment by twln1** [comment]
@stajs Relish has been released to prod as 1.3.62. 
Permission to merge?

**Comment by stajs** [comment]
@twln1 merge away. Do you know if there will be some #release-notes?

**Comment by twln1** [comment]
@stajs  There should be some coming out soon

**Pull request merged**
