### PR TITLE
create css vars for button styles, flex position the oauth signin but…

### PR DESCRIPTION
**Pull request by l0ud0gg**
…tons

ADO card: ☑️ [AB#11406](https://dev.azure.com/S72/fefacba9-96b6-4af2-a53d-050ed453e13a/_workitems/edit/11406)

## Description of work
Style the SSO buttons with default btn styles but also have css vars if they need to be changed in the shared template. Also brought default button styles in as css variables, as its currently a mission to style buttons in shared template. To test this PR you can run core template locally against staging-store-kibble.shift72.com or dl.locarnofestival.ch.

### Affected Clients
 - All clients who use Kibble

## Checklist
- [ ] CI tests are passing Github actions (inc. linting)
- [ ] Key areas of the feature outlined for context and testing
- [ ] If there are designs for this work are they noted here and in the ADO card 
- [ ] Design review
- [ ] Have checked this at multiple screen resolutions and range of browsers
- [ ] Moved ADO card to Dev/done, checked link to Github, tagged "Review"
- [ ] Updated changelog (if applicable)
- [ ] I promise to document any new feature toggles/configurations in the appropriate documentation

### CODE REVIEW

**Comment by PeculiarGoat** [comment]
Please run the linter!

**Comment by l0ud0gg** [comment]
> Please run the linter!

done

**Review by sam-shift72 — APPROVED** [review]
LGTM

**Review by PeculiarGoat — APPROVED** [review]
👍

**Pull request merged**
