### PR TITLE
added admin script, updated lang se to sr

### PR DESCRIPTION
**Pull request by brynyShift72**
[AB#6614](https://dev.azure.com/S72/fefacba9-96b6-4af2-a53d-050ed453e13a/_workitems/edit/6614) Core-template version, if --admin run first it doesn't create .kibble which it needs so added mkdir before hand. 
will need separate PR for shift72-template as file paths are different

### CODE REVIEW

**Comment by stajs** [comment]
Your sentence trailed off, as what?

> will need separate PR for shift72-template as

**Comment by brynyShift72** [comment]
> Your sentence trailed off, as what?
> 
> > will need separate PR for shift72-template as

Whoops, updated

**Comment by stajs** [comment]
Had a play with an alternative approach to try and not repeat so much, see what you think of #286

**Comment by stajs** [comment]
https://github.com/shift72/shift72-template/pull/26

**Comment by brynyShift72** [comment]
@stajs I'm going to delete this PR/Branch since where going with the other one :)

**Review by stajs — APPROVED** [review]
Approving my own work in a way lol

**Pull request merged**
